<footer class="c-footer">
  Generated by <a href="https://github.com/jikkai/cocytus">Cocytus</a>.
  Powered by <a href="https://asaki.me">Jikkai Xiao</a>
</footer>

<style>
  .c-footer {
    height: 64px;
    font-size: 12px;
    text-align: right;
  }
</style>
